### ISSUE TITLE
Include a license

### ISSUE THREAD

**Issue by Atrate** [Magisk-Modules-Alt-Repo/Better-MIUI-Icons#1]
It would be beneficial if you included a LICENSE file for your project (and mentioned in the README it only applies to the code, not the image assets).

Without a LICENSE in place, the code is implicitly All Rights Reserved, which means people cannot fork your code and legally make contributions to your repo.

EDIT:

I would suggest, as I always do, the GPLv3. Here are the instructions for including a LICENSE in your repo: https://www.gnu.org/licenses/gpl-howto.html

**Comment by SpicyChair** [comment]
Ah, thank you for the tip :) 
A GPLv3 license has been added.
